---

name: actionlint

on:
  pull_request:
    paths:
      - .github/workflows/*.yml
  push:
    paths:
      - .github/workflows/*.yml
  workflow_call:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      -
        uses: docker://rhysd/actionlint:1.7.11
        with:
          args: -color -verbose

...
