---

name: rust cargo-audit

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:

  cargo-audit:
    runs-on: ubuntu-latest

    steps:

      -
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: install cargo-audit
        uses: taiki-e/install-action@6a1bd70eaac3c8bdf093356838d7ee09fda951cf # v2.85.5
        with:
          tool: cargo-audit@0.22.2

      - name: generate Cargo.lock if missing
        if: ${{ hashFiles('Cargo.lock') == '' }}
        run: cargo generate-lockfile

      -
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          token: ${{ secrets.token }}

...
